// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package ey.managedspy;

@net.sf.jni4net.attributes.ClrType
public class RemoteObject extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected RemoteObject(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public RemoteObject() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        RemoteObject.__ctorRemoteObject0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorRemoteObject0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native String gettypeName();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void settypeName(String __set_formal);
    
    @net.sf.jni4net.attributes.ClrMethod("()[LSystem/Object;")
    public native system.Object[] getparams();
    
    @net.sf.jni4net.attributes.ClrMethod("([LSystem/Object;)V")
    public native void setparams(system.Object[] __set_formal);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native String getname();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setname(String __set_formal);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native String getassembly();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setassembly(String __set_formal);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native String getgetType();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void setgetType(String __set_formal);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Object;")
    public native system.Object getObject();
    
    public static system.Type typeof() {
        return RemoteObject.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        RemoteObject.staticType = staticType;
    }
    //</generated-proxy>
}
