// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.componentmodel;

@net.sf.jni4net.attributes.ClrType
public class AttributeCollection extends system.Object implements system.collections.ICollection, system.collections.IEnumerable {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected AttributeCollection(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("([LSystem/Attribute;)V")
    public AttributeCollection(system.Attribute[] attributes) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        AttributeCollection.__ctorAttributeCollection0(this, attributes);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("([Lsystem/Attribute;)V")
    private native static void __ctorAttributeCollection0(net.sf.jni4net.inj.IClrProxy thiz, system.Attribute[] attributes);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Array;I)V")
    public native void CopyTo(system.Array array, int index);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getCount();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Object;")
    public native system.Object getSyncRoot();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isSynchronized();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Collections/IEnumerator;")
    public native system.collections.IEnumerator GetEnumerator();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/AttributeCollection;[LSystem/Attribute;)LSystem/ComponentModel/AttributeCollection;")
    public native static AttributeCollection FromExisting(AttributeCollection existing, system.Attribute[] newAttributes);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)LSystem/Attribute;")
    public native system.Attribute getItem(int index);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Type;)LSystem/Attribute;")
    public native system.Attribute getItem(system.Type attributeType);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Attribute;)Z")
    public native boolean Contains(system.Attribute attribute);
    
    @net.sf.jni4net.attributes.ClrMethod("([LSystem/Attribute;)Z")
    public native boolean Contains(system.Attribute[] attributes);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Attribute;)Z")
    public native boolean Matches(system.Attribute attribute);
    
    @net.sf.jni4net.attributes.ClrMethod("([LSystem/Attribute;)Z")
    public native boolean Matches(system.Attribute[] attributes);
    
    public static system.Type typeof() {
        return AttributeCollection.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        AttributeCollection.staticType = staticType;
    }
    //</generated-proxy>
}
