// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.componentmodel;

@net.sf.jni4net.attributes.ClrType
public class EventDescriptor extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected EventDescriptor(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected EventDescriptor() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Type;")
    public native system.Type getComponentType();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Type;")
    public native system.Type getEventType();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isMulticast();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/Delegate;)V")
    public native void AddEventHandler(system.Object component, system.Delegate value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/Delegate;)V")
    public native void RemoveEventHandler(system.Object component, system.Delegate value);
    
    public static system.Type typeof() {
        return EventDescriptor.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        EventDescriptor.staticType = staticType;
    }
    //</generated-proxy>
}
