// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.componentmodel;

@net.sf.jni4net.attributes.ClrType
public class PropertyDescriptorCollection extends system.Object implements system.collections.ICollection, system.collections.IEnumerable, system.collections.IList {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected PropertyDescriptorCollection(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("([LSystem/ComponentModel/PropertyDescriptor;)V")
    public PropertyDescriptorCollection(PropertyDescriptor[] properties) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        PropertyDescriptorCollection.__ctorPropertyDescriptorCollection0(this, properties);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("([LSystem/ComponentModel/PropertyDescriptor;Z)V")
    public PropertyDescriptorCollection(PropertyDescriptor[] properties, boolean readOnly) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        PropertyDescriptorCollection.__ctorPropertyDescriptorCollection1(this, properties, readOnly);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("([Lsystem/componentmodel/PropertyDescriptor;)V")
    private native static void __ctorPropertyDescriptorCollection0(net.sf.jni4net.inj.IClrProxy thiz, PropertyDescriptor[] properties);
    
    @net.sf.jni4net.attributes.ClrMethod("([Lsystem/componentmodel/PropertyDescriptor;Z)V")
    private native static void __ctorPropertyDescriptorCollection1(net.sf.jni4net.inj.IClrProxy thiz, PropertyDescriptor[] properties, boolean readOnly);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Array;I)V")
    public native void CopyTo(system.Array array, int index);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getCount();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Object;")
    public native system.Object getSyncRoot();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isSynchronized();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Collections/IEnumerator;")
    public native system.collections.IEnumerator GetEnumerator();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)LSystem/Object;")
    public native system.Object getItem(int index);
    
    @net.sf.jni4net.attributes.ClrMethod("(ILSystem/Object;)V")
    public native void setItem(int index, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)I")
    public native int Add(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)Z")
    public native boolean Contains(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native void Clear();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isReadOnly();
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean isFixedSize();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)I")
    public native int IndexOf(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(ILSystem/Object;)V")
    public native void Insert(int index, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)V")
    public native void Remove(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void RemoveAt(int index);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)LSystem/Object;")
    public native system.Object getItem(system.Object key);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/Object;)V")
    public native void setItem(system.Object key, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Collections/ICollection;")
    public native system.collections.ICollection getKeys();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Collections/ICollection;")
    public native system.collections.ICollection getValues();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/Object;)V")
    public native void Add(system.Object key, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/ComponentModel/PropertyDescriptor;")
    public native PropertyDescriptor getItem(String name);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/PropertyDescriptor;)I")
    public native int Add(PropertyDescriptor value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/PropertyDescriptor;)Z")
    public native boolean Contains(PropertyDescriptor value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;Z)LSystem/ComponentModel/PropertyDescriptor;")
    public native PropertyDescriptor Find(String name, boolean ignoreCase);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/PropertyDescriptor;)I")
    public native int IndexOf(PropertyDescriptor value);
    
    @net.sf.jni4net.attributes.ClrMethod("(ILSystem/ComponentModel/PropertyDescriptor;)V")
    public native void Insert(int index, PropertyDescriptor value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/PropertyDescriptor;)V")
    public native void Remove(PropertyDescriptor value);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/ComponentModel/PropertyDescriptorCollection;")
    public native PropertyDescriptorCollection Sort();
    
    @net.sf.jni4net.attributes.ClrMethod("([LSystem/String;)LSystem/ComponentModel/PropertyDescriptorCollection;")
    public native PropertyDescriptorCollection Sort(String[] names);
    
    @net.sf.jni4net.attributes.ClrMethod("([LSystem/String;LSystem/Collections/IComparer;)LSystem/ComponentModel/PropertyDescriptorCollection;")
    public native PropertyDescriptorCollection Sort(String[] names, system.Object comparer);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Collections/IComparer;)LSystem/ComponentModel/PropertyDescriptorCollection;")
    public native PropertyDescriptorCollection Sort(system.Object comparer);
    
    public static system.Type typeof() {
        return PropertyDescriptorCollection.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        PropertyDescriptorCollection.staticType = staticType;
    }
    //</generated-proxy>
}
