// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.componentmodel;

@net.sf.jni4net.attributes.ClrType
public class TypeConverter extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected TypeConverter(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public TypeConverter() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        TypeConverter.__ctorTypeConverter0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorTypeConverter0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Type;)Z")
    public native boolean CanConvertFrom(system.Type sourceType);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Type;)Z")
    public native boolean CanConvertFrom(system.Object context, system.Type sourceType);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Type;)Z")
    public native boolean CanConvertTo(system.Type destinationType);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Type;)Z")
    public native boolean CanConvertTo(system.Object context, system.Type destinationType);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)LSystem/Object;")
    public native system.Object ConvertFrom(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Globalization/CultureInfo;LSystem/Object;)LSystem/Object;")
    public native system.Object ConvertFrom(system.Object context, system.Object culture, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/Object;")
    public native system.Object ConvertFromInvariantString(String text);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/String;)LSystem/Object;")
    public native system.Object ConvertFromInvariantString(system.Object context, String text);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)LSystem/Object;")
    public native system.Object ConvertFromString(String text);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/String;)LSystem/Object;")
    public native system.Object ConvertFromString(system.Object context, String text);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Globalization/CultureInfo;LSystem/String;)LSystem/Object;")
    public native system.Object ConvertFromString(system.Object context, system.Object culture, String text);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/Type;)LSystem/Object;")
    public native system.Object ConvertTo(system.Object value, system.Type destinationType);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Globalization/CultureInfo;LSystem/Object;LSystem/Type;)LSystem/Object;")
    public native system.Object ConvertTo(system.Object context, system.Object culture, system.Object value, system.Type destinationType);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)LSystem/String;")
    public native String ConvertToInvariantString(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Object;)LSystem/String;")
    public native String ConvertToInvariantString(system.Object context, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)LSystem/String;")
    public native String ConvertToString(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Object;)LSystem/String;")
    public native String ConvertToString(system.Object context, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Globalization/CultureInfo;LSystem/Object;)LSystem/String;")
    public native String ConvertToString(system.Object context, system.Object culture, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Collections/IDictionary;)LSystem/Object;")
    public native system.Object CreateInstance(system.collections.IDictionary propertyValues);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Collections/IDictionary;)LSystem/Object;")
    public native system.Object CreateInstance(system.Object context, system.collections.IDictionary propertyValues);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean GetCreateInstanceSupported();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;)Z")
    public native boolean GetCreateInstanceSupported(system.Object context);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)LSystem/ComponentModel/PropertyDescriptorCollection;")
    public native system.componentmodel.PropertyDescriptorCollection GetProperties(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Object;)LSystem/ComponentModel/PropertyDescriptorCollection;")
    public native system.componentmodel.PropertyDescriptorCollection GetProperties(system.Object context, system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Object;[LSystem/Attribute;)LSystem/ComponentModel/PropertyDescriptorCollection;")
    public native system.componentmodel.PropertyDescriptorCollection GetProperties(system.Object context, system.Object value, system.Attribute[] attributes);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean GetPropertiesSupported();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;)Z")
    public native boolean GetPropertiesSupported(system.Object context);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Collections/ICollection;")
    public native system.collections.ICollection GetStandardValues();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;)LSystem/ComponentModel/TypeConverter+StandardValuesCollection;")
    public native system.Object GetStandardValues(system.Object context);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean GetStandardValuesExclusive();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;)Z")
    public native boolean GetStandardValuesExclusive(system.Object context);
    
    @net.sf.jni4net.attributes.ClrMethod("()Z")
    public native boolean GetStandardValuesSupported();
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;)Z")
    public native boolean GetStandardValuesSupported(system.Object context);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;)Z")
    public native boolean IsValid(system.Object value);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/ComponentModel/ITypeDescriptorContext;LSystem/Object;)Z")
    public native boolean IsValid(system.Object context, system.Object value);
    
    public static system.Type typeof() {
        return TypeConverter.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        TypeConverter.staticType = staticType;
    }
    //</generated-proxy>
}
