// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system;

@net.sf.jni4net.attributes.ClrType
public abstract class EventHandler extends MulticastDelegate {
    
    //<generated-proxy>
    private static Type staticType;
    
    protected EventHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected EventHandler() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/EventArgs;)V")
    public abstract void Invoke(Object sender, Object e);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/EventArgs;LSystem/AsyncCallback;LSystem/Object;)LSystem/IAsyncResult;")
    public IAsyncResult BeginInvoke(Object sender, Object e, AsyncCallback callback, Object object) {
        throw new NotImplementedException();
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IAsyncResult;)V")
    public void EndInvoke(IAsyncResult result) {
        throw new NotImplementedException();
    }
    
    public static Type typeof() {
        return EventHandler.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, Type staticType) {
        EventHandler.staticType = staticType;
    }
    //</generated-proxy>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __EventHandler extends EventHandler {
    
    protected __EventHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/EventArgs;)V")
    public native void Invoke(Object sender, Object e);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/EventArgs;LSystem/AsyncCallback;LSystem/Object;)LSystem/IAsyncResult;")
    public native IAsyncResult BeginInvoke(Object sender, Object e, AsyncCallback callback, Object object);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IAsyncResult;)V")
    public native void EndInvoke(IAsyncResult result);
}
//</generated-proxy>
