// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package microsoft.managedspy;

@net.sf.jni4net.attributes.ClrType
public abstract class ControlProxyEventHandler extends system.MulticastDelegate {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ControlProxyEventHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected ControlProxyEventHandler() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LMicrosoft/ManagedSpy/ProxyEventArgs;)V")
    public abstract void Invoke(system.Object sender, ProxyEventArgs ed);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LMicrosoft/ManagedSpy/ProxyEventArgs;LSystem/AsyncCallback;LSystem/Object;)LSystem/IAsyncResult;")
    public system.IAsyncResult BeginInvoke(system.Object sender, ProxyEventArgs ed, system.AsyncCallback callback, system.Object obj) {
        throw new system.NotImplementedException();
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IAsyncResult;)V")
    public void EndInvoke(system.IAsyncResult result) {
        throw new system.NotImplementedException();
    }
    
    public static system.Type typeof() {
        return ControlProxyEventHandler.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        ControlProxyEventHandler.staticType = staticType;
    }
    //</generated-proxy>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __ControlProxyEventHandler extends ControlProxyEventHandler {
    
    protected __ControlProxyEventHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LMicrosoft/ManagedSpy/ProxyEventArgs;)V")
    public native void Invoke(system.Object sender, ProxyEventArgs ed);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LMicrosoft/ManagedSpy/ProxyEventArgs;LSystem/AsyncCallback;LSystem/Object;)LSystem/IAsyncResult;")
    public native system.IAsyncResult BeginInvoke(system.Object sender, ProxyEventArgs ed, system.AsyncCallback callback, system.Object obj);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IAsyncResult;)V")
    public native void EndInvoke(system.IAsyncResult result);
}
//</generated-proxy>
