// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package microsoft.managedspy;

@net.sf.jni4net.attributes.ClrType
public class ProxyEventArgs extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ProxyEventArgs(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/ComponentModel/EventDescriptor;LSystem/EventArgs;)V")
    public ProxyEventArgs(system.componentmodel.EventDescriptor ed, system.Object args) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        ProxyEventArgs.__ctorProxyEventArgs0(this, ed, args);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Lsystem/componentmodel/EventDescriptor;Lsystem/Object;)V")
    private native static void __ctorProxyEventArgs0(net.sf.jni4net.inj.IClrProxy thiz, system.componentmodel.EventDescriptor ed, system.Object args);
    
    public static system.Type typeof() {
        return ProxyEventArgs.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        ProxyEventArgs.staticType = staticType;
    }
    //</generated-proxy>
}
