// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system.windows.forms;

@net.sf.jni4net.attributes.ClrType
public class MouseEventArgs extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected MouseEventArgs(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(LSystem/Windows/Forms/MouseButtons;IIII)V")
    public MouseEventArgs(system.Enum button, int clicks, int x, int y, int delta) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        MouseEventArgs.__ctorMouseEventArgs0(this, button, clicks, x, y, delta);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(Lsystem/Enum;IIII)V")
    private native static void __ctorMouseEventArgs0(net.sf.jni4net.inj.IClrProxy thiz, system.Enum button, int clicks, int x, int y, int delta);
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Windows/Forms/MouseButtons;")
    public native system.Enum getButton();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getClicks();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getX();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getY();
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getDelta();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Drawing/Point;")
    public native system.ValueType getLocation();
    
    public static system.Type typeof() {
        return MouseEventArgs.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        MouseEventArgs.staticType = staticType;
    }
    //</generated-proxy>
}
