// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package managedspylib;

@net.sf.jni4net.attributes.ClrType
public class MessageFilters extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected MessageFilters(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected MessageFilters() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void Initialize();
    
    public static system.Type typeof() {
        return MessageFilters.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        MessageFilters.staticType = staticType;
    }
    //</generated-proxy>
}
